### PR TITLE
add nestjs examples

### PR DESCRIPTION
**Pull request by nitedani**
Added two examples for NestJS.

1. Simple NestJS app
2. NestJS + vite-plugin-ssr integration

NestJS requires decorator metadata to work. The swc rollup plugin handles that, but stackblitz can't run swc.

### CODE REVIEW

**Comment by cyco130** [comment]
The CI fail is caused by a pnpm update. I'll fix it tomorrow. Thanks for this!

**Comment by cyco130** [comment]
I can't run the examples. `nestjs` complains:

```
reflect-metadata doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

but a browser reload seems to run the app anyway. `nestjs-vite-plugin-ssr` complains about the same but also cannot find `express`. I assume it's WIP so I'm not touching it just yet :)

**Comment by nitedani** [comment]
I fixed the express and reflect-metadata errors, for the NestJS 404: https://github.com/cyco130/vavite/pull/15

**Comment by cyco130** [comment]
> for the NestJS 404: #15

Oh, great catch. I'll have a look today, thanks!

**Comment by cyco130** [comment]
Could you update the lock file so I can run the CI? Just do `pnpm install` and commit the file `pnpm-lock.yaml`.

**Comment by cyco130** [comment]
Merged, awesome, thank you! The other PR didn't solve the 404 problem, I'll have a better look on the weekend.

**Pull request merged**
